package com.yunjun.productone.mapper;

import com.yunjun.productone.model.Code;
import com.yunjun.productone.model.CodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    Code selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int updateByPrimaryKeySelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    int updateByPrimaryKey(Code record);
}