server:
  port: 8085
spring:
  application:
    name: productRedis
  #redis????#
  data:
    redis:
      database: 0
      host: 192.168.0.108
      port: 6379
      username:
      password:
      timeout: 4000
      lettuce:
        pool:
          #???????????????????? ?? 8
          max-active: 8
          # ??????????? ?? 8
          max-idle: 8
          # ??????????????????????? ?? -1
          max-wait: -1
          # ??????????? ?? 0
          min-idle: 0


