package com.yunjun.productone.model;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.desc
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.url
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.is_delete
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.create_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.update_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.version
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.code
     *
     * @return the value of permission.code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.code
     *
     * @param code the value for permission.code
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.desc
     *
     * @return the value of permission.desc
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.desc
     *
     * @param desc the value for permission.desc
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.url
     *
     * @return the value of permission.url
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.url
     *
     * @param url the value for permission.url
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.is_delete
     *
     * @return the value of permission.is_delete
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.is_delete
     *
     * @param isDelete the value for permission.is_delete
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.create_date
     *
     * @return the value of permission.create_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.create_date
     *
     * @param createDate the value for permission.create_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.update_date
     *
     * @return the value of permission.update_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.update_date
     *
     * @param updateDate the value for permission.update_date
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.version
     *
     * @return the value of permission.version
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.version
     *
     * @param version the value for permission.version
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sun Feb 26 21:00:41 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", desc=").append(desc);
        sb.append(", url=").append(url);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}